### ISSUE TITLE
getTempo overall score vs. individual instrument

### ISSUE THREAD

**Issue by galinabee** [MegaArman/toscanini#32]
Taking a look at Vivaldi's Winter, for individual instruments, the overall score statements are not included for the individual instruments. Currently, when asked for an instrument, it does not return the overall score's tempo contribution, only the instrument's.

**Comment by LinusTorvald** [comment]
Wow that's a really insightful finding, how would you like to work on the kernel? We can always use more tempo in open source.

**Comment by MegaArman** [comment]
causes an issue with getTempos(instrumentName)
