### ISSUE TITLE
getScoreLength

### ISSUE THREAD

**Issue by MegaArman** [MegaArman/Toscanini#41]
ex:
toscanini.getScoreLength(); // => {"measures": 200, "time": "20m32s"}

^ the exact time formatting could be different. Time can be tricky to compute as it requires consideration for tempos, # measures, and time signatures

**Comment by galinabee** [comment]
Seems like overall, it is 120 bpm if no tempo is specified, but some playbacks in Musescore, Finale, or Sibelius, do not interpret it in the same manner, because there's not much specificity within a MusicXML document. 
https://musescore.org/en/node/9422

**Comment by galinabee** [comment]
Also, time for playback is only interpreted for tempo changes, not word changes (ex. there has to be a marking of quarter note now set to 100, and MusicXML does not account for changes like ritardando).

**Comment by MegaArman** [comment]
usability concerns:
-more use case dependent 
	ex:
		 search engine (high level info),
		 iterator => score annotator – ex: chords 
		 ^^^ we know this requires a different parser

Technical concerns:
-extraction of info from musicxml 
-providing an abstraction useful for programmers

getScoreLength:
-does not require a different parser, but difficult with current parser => 
	Could using a different parser make things easier for this function? 
		It’s going to be a challenging exraction process regardless, but it MAY be somewhat 			easier w new parser
-similar changes the iterator faces regarding very positional information in the score

conclusion: due to similar challenges faced w/ iterator we will postpone getScoreLength to avoid duplication of work in the long run, instead we will have getNumberOfMeasures that with the existing getTempos can

**Comment by MegaArman** [comment]
(+) We found NodeElementTree to be a helpful module for parsing xml as it supports XPATHS
(-) It will be very difficult to account for repeats and alternate endings etc. It would be easier to simply use a CLI to generate a MIDI file and get the length of that MIDI file.
